### ISSUE TITLE
run generator fail in yo

### ISSUE THREAD

**Issue by tankiJong** [peoplewareDo/generator-ng2-seed-advanced#6]
I install the generator failed with npm first.

So I then install it with yarn. I received several warnings but I don't think it make sense.
```
yarn global v0.16.1
[1/4] 🔍  Resolving packages...
warning generator-ng2-seed-advanced > angular2-seed-advanced > es6-module-loader@0.17.11: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Incorrect peer dependency "@angular/core@^2.0.0".
warning Incorrect peer dependency "rxjs@^5.0.0-beta.12".
warning Incorrect peer dependency "rxjs@^5.0.0-beta.12".
[4/4] 📃  Building fresh packages...
warning generator-ng2-seed-advanced@1.0.0 has no binaries
✨  Done in 66.85s.
```

When I run the cmd `yo  ng2-seed-advanced`

the following words are printed.
```

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the solid   │
    |--(o)--|    │ generator-ng2-seed-advan │
   `---------´   │      ced generator!      │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What is your project name? (your-project)

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at child.Base.prompt (/usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/yeoman-generator/lib/base.js:232:45)
    at child.prompting (/usr/local/lib/node_modules/generator-ng2-seed-advanced/generators/app/index.js:51:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/yeoman-generator/lib/base.js:432:9
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

Is that caused because of my using yarn? But I tried run npm install then and installed correctly. The error still occurs.

**Comment by victorsosa** [comment]
I will update the seed project (aka template project that should fix the issue)

**Comment by victorsosa** [comment]
Please try again and let me know if you got any issue, reopen this in any case of issue.

**Comment by victorsosa** [comment]
I found that this was reported in the issue #5

**Comment by tankiJong** [comment]
Sorry for my late response. 
Actually, I solved this problem through completely re-install the yeoman and other related dependencies.

Wish this could work for other people :)
