### ISSUE TITLE
Can not install generator-ng2-seed-advanced

### ISSUE THREAD

**Issue by kiranchowdhury** [peoplewareDo/generator-ng2-seed-advanced#9]
Hello!
On my mac I am getting this error while running sudo npm install -g generator-ng2-seed-advanced
> angular2-seed-advanced@1.0.0 postinstall /usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/angular2-seed-advanced
> typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js

/usr/local/lib/node_modules/typings/node_modules/configstore/index.js:49
			throw err;
			^

Error: EACCES: permission denied, open '/Users/kiranchowdhury/.config/configstore/typings.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Configstore.get all [as all] (/usr/local/lib/node_modules/typings/node_modules/configstore/index.js:30:25)
    at new Configstore (/usr/local/lib/node_modules/typings/node_modules/configstore/index.js:25:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/typings/node_modules/typings-core/dist/utils/store.js:5:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by victorsosa** [comment]
this is a permission issue; please try using sudo
